spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(N6G22iNIGwVJsc1B+dPUcKyr00EdPnbEHUNn85QtbCxyLitR6FcTDnr3QApRUOXwFP7RoZBF1R+ReKeEwllWPnz83Fim7Qwq4aEIz7y8ZXJjrfGNuLMZ4o4CF0gFL6iPf3nGRbZ+evU=)
    username: ENC(rbAYXvnEtHLKTZhqKbLtHA==)
    password: ENC(WhT4M4/oia1FZqQ/BES/jw==)
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
