spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(6yjUto3Z/eV8iFQkTt4RKMB5HHEAUzMaoziqfTO5kv+wje6Xr0lxjrVB/TcOnkgkNIhYdl8yYI3VgCtyvkorTTmsOYuQPp4ovxSbwns3Vv0=)
    username: ENC(Tg7JeTTikt6xgGQ6qWXJWQ==)
    password: ENC(5f91ekHunQTSOjCGztNYRQ+KAbIJVg4v)
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework.security: DEBUG
