spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Wl6IZoaBCe3o1mVLnxPrPL/vNeC7Gufqws4qiOKFTFqKPP4H6PuuHAfhSeTr+lzy01yiWu/GtdtK2QjOYEfJz6nmxGXoxk7xuITeSfeVRF7nco8GjJg6pF8CEtoUub1q9I0R3l7S9I6LN+fR7uO32ICWTQ1uUZ8q8jc7avMgRdi/uEahjpeqenqSGlAs6VIqFgpCiFBckmilR6QW+2aX2CilrNsj+bgtn6zD7LPUIlw=)
    username: ENC(PhyaRJCJP89U3bl2A9njuA==)
    password: ENC(RqQ+m97Mi+ianfhwxg0JI4EOZk3cPdzh)
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework.security: TRACE
    org.mapstruct: DEBUG
jwt:
  secret: ENC(7EcTP9qkkVTr42yxPyHfKOOy6A/zDElhrnJk0bai0WGvGH+h7tu925YOJ+bafJ+6ey9VxQ5uq0gWYU8gfvXr8g9F9pIHp8tiTdty/qGinSU=)
